version: '3.7'

services: 
  hath:
    image: openjdk:8-jre-alpine
    container_name: hath
    restart: unless-stopped
    env_file:
      - ../env_file.d/env.id
    volumes:
      - ./hath-client:/hath-client
    ports:
      - '0.0.0.0:443:443'
    working_dir: /hath-client
    command: java -jar HentaiAtHome.jar

networks:
  default:
    name: $DEFAULT_NETWORK
    external: true
