version: '3.7'

services: 
  latex:
    build: ./latex
    container_name: latex
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./latex/workspace:/root/
      - /root/.ssh/authorized_keys:/root/.ssh/authorized_keys
    ports:
<<<<<<< HEAD
      - '0.0.0.0:1201:22'
=======
      - '0.0.0.0:2222:22'
>>>>>>> fe0e68620e44252758713c69c570b9d0bbe4f7c6
    restart: unless-stopped
