version: '3'

services: 
  latex:
    build: ./latex
    image: vscode-latex
    container_name: latex
    restart: unless-stopped
    env_file:
      - ../env_file.d/env.id 
    volumes:
      - ./latex/workspace:/home/arikoi/
      - ~/.ssh/authorized_keys:/home/arikoi/.ssh/authorized_keys
    ports:
      - '0.0.0.0:1201:22'

networks:
  default:
    name: $DEFAULT_NETWORK
    external: true
