version: '3.7'

services: 
  latex:
    build: ./latex
    image: vscode-latex
    container_name: latex
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./latex/workspace:/home/arikoi/
      - ~/.ssh/authorized_keys:/home/arikoi/.ssh/authorized_keys
    ports:
      - '0.0.0.0:1201:22'
    restart: unless-stopped
