version: "3.7"
services:
  tweebot:
    build: ./tweebot
    image: py-tweebot
    container_name: tweebot
    volumes:
      - ./tweebot/screen_name.list:/screen_name.list
    restart: unless-stopped
    command: ./main
