version: '3.7'

services: 
    wireguard:
        image: linuxserver/wireguard
        container_name: wireguard
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
            - SERVERPORT=51820
            - PEERS=2 #optional
            - PEERDNS=auto #optional
            - INTERNAL_SUBNET=10.10.0.0 #optional
            - ALLOWEDIPS=10.10.0.0/8 #optional
        volumes:
            - /lib/modules:/lib/modules
            - /home/arikoi/docker/wireguard/config:/config
        ports:
            - 51820:51820/udp
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
        restart: unless-stopped
        